MNT: Re-rendered with conda-smithy 3.1.12 and pinning 2018.08.31

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -4,34 +4,60 @@
 language: generic
 
 os: osx
-osx_image: beta-xcode6.1
+osx_image: xcode6.4
 
 env:
+  matrix:
+    - CONFIG=osx_
+
   global:
     # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
     - secure: "causQXav5twIGnY8CEVztYNJQhUNUZzC8DL7hnbbCPUENuDxT4ptbrEoWzN33FSaxFMUP5WssZFhd5cauj8cqwjroGmp0fdnVmTrlMJJkLX9W9TSkcibNiEf0/u9Bco3KF25+K2LrcdnQ8cfkvl5uSinotMtB7aEFgcSPAeKKZY9uSA7iUE0nloR4OygfkucenQ+TD6HPPU9LoBPk1REMkyayu+6BUReYRZwEA1/vVwVYEol87jFgBtZO+bQvdYwn/Z9aZFzN5J6emtC0/fqANUknf09QiAPHwcfj2e8eYknP09BJqxfgy1bAZjdXYVkCrmvJszHJLDzsuMDjAq5DeCMXEW2HEjdbnFXHiKuEP5rDEQn/MffYKXha11xCl4n3Aq7kGt3B3vh3di4+Ws2yipntOhjQ+X4Tvq9SbE060tYuakGAxDlohbeaToNKvuJZJSnO6457keMErryoj5aDHosdoMxyrOU+Jq0YWDXGUvgaF9SYgM4J/e3LU0VPpxrEOV6bn1s/rjD52uil5ACIKLvBFn2gtEpb3+6fGJ6X6FdhNtSG6KWIClmDxxMDAKzwnV44vm8zNyPkgZpIH7tp4LBtBwt5SkoHmtyzACUeV/REEj7crMUdlTbcEjv6LD1zST7q6NsC9Ekv7zIBFOonE7BRhtHmx/Z5mwXFhmkQn4="
 
 
 before_install:
+    # Fast finish the PR.
+    - |
+      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
+          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1
+
     # Remove homebrew.
-    - brew remove --force $(brew list)
-    - brew cleanup -s
-    - rm -rf $(brew --cache)
+    - |
+      echo ""
+      echo "Removing homebrew from Travis CI to avoid conflicts."
+      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
+      chmod +x ~/uninstall_homebrew
+      ~/uninstall_homebrew -fq
+      rm ~/uninstall_homebrew
+
 
 install:
+    # Install Miniconda.
     - |
+      echo ""
+      echo "Installing a fresh version of Miniconda."
       MINICONDA_URL="https://repo.continuum.io/miniconda"
       MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
       curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
       bash $MINICONDA_FILE -b
 
+    # Configure conda.
+    - |
+      echo ""
+      echo "Configuring conda."
       source /Users/travis/miniconda3/bin/activate root
-      conda config --add channels conda-forge
-      conda config --set show_channel_urls true
-      conda install --yes --quiet conda-forge-build-setup
+
+      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
+      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml
+
       source run_conda_forge_build_setup
 
-script:
-  - conda build ./recipe
+    # compiler cleanup
+    - |
+      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml
 
-  - upload_or_check_non_existence ./recipe conda-forge --channel=main
+script:
+  # generate the build number clobber
+  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
+  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
+  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
